version: '2'
services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=mypass

    go:
        build: .
        environment:
          -  POSTGRES_DB_HOST=db
          -  POSTGRES_DB_PORT=5432
          -  POSTGRES_DB_PASSWORD=mypass
        ports:
            - "8080"
        depends_on:
            - db